version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    restart: always
    env_file:
      - ./config/postgres/postgres.env
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./config/postgres/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432/tcp
  odoo:
    container_name: odoo
    build: .
    platform: linux/amd64 # for arm mac, required this
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres:postgres
    volumes:
      - ./addons:/mnt/extra-addons
      - ./config/odoo:/etc/odoo
      - odoo-web-data:/var/lib/odoo
    ports:
      - 8069:8069/tcp
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:8069
    depends_on:
      - odoo
    restart: always
    links:
      - odoo:odoo
volumes:
  db-data:
  metabase-data:
  odoo-web-data:
