version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    restart: always
    env_file:
      - ./config/postgres/postgres.env
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./config/postgres/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432/tcp
    # networks:
    #   - postgres
  odoo:
    container_name: odoo
    build: .
    platform: linux/amd64 # for arm mac, required this
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres:postgres
    volumes:
      - ./addons:/mnt/extra-addons
      - ./config/odoo:/etc/odoo
      - odoo-web-data:/var/lib/odoo
    ports:
      - 8069:8069/tcp
  odoo1:
    container_name: odoo1
    build: .
    platform: linux/amd64 # for arm mac, required this
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres:postgres
    volumes:
      - ./addons:/mnt/extra-addons
      - ./config/odoo1:/etc/odoo
      - odoo-web-data1:/var/lib/odoo
    ports:
      - 8061:8069/tcp
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:8069
    depends_on:
      - odoo
    restart: always
    links:
      - odoo:odoo
  # pgadmin:
  #   container_name: pgadmin_container
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
  #     PGADMIN_CONFIG_SERVER_MODE: 'False'
  #   volumes:
  #      - pgadmin:/var/lib/pgadmin

  #   ports:
  #     - "${PGADMIN_PORT:-5050}:80"
  #   networks:
  #     - postgres
  #   restart: unless-stopped
# networks:
#   postgres:
#     driver: bridge
volumes:
  db-data:
  metabase-data:
  odoo-web-data:
  odoo-web-data1:
  # pgadmin:

